### ISSUE TITLE
Do I need to write the JS for it to work? it's displaying blank space.

### ISSUE THREAD

**Issue by KaitoXion** [TahaSh/vue-expandable-image#3]
Do I need to write the JS for it to work?
sorry, am a noop.

included code:
`<expandable-image src="../components/img/brandIcon.png" style=" width: auto;"></expandable-image>`

![image](https://user-images.githubusercontent.com/23281263/59762788-986f7080-92ca-11e9-92eb-0b67115c9561.png)

![image](https://user-images.githubusercontent.com/23281263/59763106-6f031480-92cb-11e9-962e-428bc67a744c.png)

**Comment by TahaSh** [comment]
@KaitoXion Have you installed the plugin? https://github.com/TahaSh/vue-expandable-image#commonjs-webpackbrowserify

You don't have to implement anything. Just import and install the plugin as described in the docs.

**Comment by KaitoXion** [comment]
I have installed the plugin.

added this code into main.js; so it should already been declared global based on Vue.js documentation.
```
import VueExpandableImage from 'vue-expandable-image'
Vue.use(VueExpandableImage)
```

after that. I move on to adding;
`<expandable-image src="../components/img/brandIcon.png" style=" width: auto;"></expandable-image>`

in the template tag. 
so, I actually don't have to include the JS as shown in the given CodePen?https://codepen.io/tahazsh/pen/aMbooL

**Comment by TahaSh** [comment]
@KaitoXion is it still not working?

**Comment by TahaSh** [comment]
@KaitoXion it turned out you're specifying a relative path for your image without loading it through Webpack first. [Here's how you can fix it](https://github.com/TahaSh/vue-expandable-image#the-image-doesnt-load-for-you).
