### ISSUE TITLE
Scope issue with injected css for svg path

### ISSUE THREAD

**Issue by glr2019** [TahaSh/vue-expandable-image#4]
This is great, thanks for writing this.   There is one issue I have come across, the css being injected (specifically: `svg path{fill:#fff}`  is affecting ALL of the font awesome icons in the view.  How can I go about limiting the scope of that css?  Thanks.

**Comment by glr2019** [comment]
BTW, simply commenting out that part of the injected css solved my issue,  however it is not very portable unless I fork this, or recreate the component based on your code within my project.

**Comment by TahaSh** [comment]
This issue is fixed in v0.0.2
