### ISSUE TITLE
Close automatically click black area

### ISSUE THREAD

**Issue by GMolini** [TahaSh/vue-expandable-image#7]
Would it be possible to add an option so that when you click on the black part it automatically closes?

**Comment by TahaSh** [comment]
@GMolini it's now supported in version `0.1.0`. So just update the plugin to that version, and then use the `close-on-background-click` prop, like this:

``` html
<expandable-image
  ...
  :close-on-background-click="true"
/>
```

**Comment by GMolini** [comment]
ok thanks!
